CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       nome VARCHAR(100) NOT NULL,

                       email VARCHAR(254) NOT NULL UNIQUE,

                       password VARCHAR(255) NOT NULL,

                       matricula VARCHAR(11) NOT NULL UNIQUE,

                       cargo VARCHAR(30) NOT NULL
);
